<?php

namespace ContainerBGMLLhV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D_WhzDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._d.whzD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._d.whzD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AuthenticatorController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\AuthenticatorController::login()', 'getAuthenticatorControllerloginService', true],
            'App\\Controller\\AuthenticatorController::onLogout' => ['privates', '.service_locator.rlkk1pd.App\\Controller\\AuthenticatorController::onLogout()', 'getAuthenticatorControlleronLogoutService', true],
            'App\\Controller\\AuthenticatorController::register' => ['privates', '.service_locator.ST9fez2.App\\Controller\\AuthenticatorController::register()', 'getAuthenticatorControllerregisterService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.egipcEH.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\PrestationController::index' => ['privates', '.service_locator.qCVllgb.App\\Controller\\PrestationController::index()', 'getPrestationControllerindexService', true],
            'App\\Controller\\PrestationController::edit' => ['privates', '.service_locator.2ibWYT8.App\\Controller\\PrestationController::edit()', 'getPrestationControllereditService', true],
            'App\\Controller\\PrestationController::delete' => ['privates', '.service_locator.2ibWYT8.App\\Controller\\PrestationController::delete()', 'getPrestationControllerdeleteService', true],
            'App\\Controller\\PrestationController::add' => ['privates', '.service_locator.egipcEH.App\\Controller\\PrestationController::add()', 'getPrestationControlleraddService', true],
            'App\\Controller\\PrestationController::my_prestations' => ['privates', '.service_locator.egipcEH.App\\Controller\\PrestationController::my_prestations()', 'getPrestationControllermyPrestationsService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AuthenticatorController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\AuthenticatorController::login()', 'getAuthenticatorControllerloginService', true],
            'App\\Controller\\AuthenticatorController:onLogout' => ['privates', '.service_locator.rlkk1pd.App\\Controller\\AuthenticatorController::onLogout()', 'getAuthenticatorControlleronLogoutService', true],
            'App\\Controller\\AuthenticatorController:register' => ['privates', '.service_locator.ST9fez2.App\\Controller\\AuthenticatorController::register()', 'getAuthenticatorControllerregisterService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.egipcEH.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\PrestationController:index' => ['privates', '.service_locator.qCVllgb.App\\Controller\\PrestationController::index()', 'getPrestationControllerindexService', true],
            'App\\Controller\\PrestationController:edit' => ['privates', '.service_locator.2ibWYT8.App\\Controller\\PrestationController::edit()', 'getPrestationControllereditService', true],
            'App\\Controller\\PrestationController:delete' => ['privates', '.service_locator.2ibWYT8.App\\Controller\\PrestationController::delete()', 'getPrestationControllerdeleteService', true],
            'App\\Controller\\PrestationController:add' => ['privates', '.service_locator.egipcEH.App\\Controller\\PrestationController::add()', 'getPrestationControlleraddService', true],
            'App\\Controller\\PrestationController:my_prestations' => ['privates', '.service_locator.egipcEH.App\\Controller\\PrestationController::my_prestations()', 'getPrestationControllermyPrestationsService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AuthenticatorController::login' => '?',
            'App\\Controller\\AuthenticatorController::onLogout' => '?',
            'App\\Controller\\AuthenticatorController::register' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\PrestationController::index' => '?',
            'App\\Controller\\PrestationController::edit' => '?',
            'App\\Controller\\PrestationController::delete' => '?',
            'App\\Controller\\PrestationController::add' => '?',
            'App\\Controller\\PrestationController::my_prestations' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AuthenticatorController:login' => '?',
            'App\\Controller\\AuthenticatorController:onLogout' => '?',
            'App\\Controller\\AuthenticatorController:register' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\PrestationController:index' => '?',
            'App\\Controller\\PrestationController:edit' => '?',
            'App\\Controller\\PrestationController:delete' => '?',
            'App\\Controller\\PrestationController:add' => '?',
            'App\\Controller\\PrestationController:my_prestations' => '?',
        ]);
    }
}
