<?php

namespace ContainerBGMLLhV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestationTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PrestationType' shared autowired service.
     *
     * @return \App\Form\PrestationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PrestationType.php';

        return $container->privates['App\\Form\\PrestationType'] = new \App\Form\PrestationType();
    }
}
