<?php

namespace ContainerBGMLLhV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestationControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2ibWYT8.App\Controller\PrestationController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2ibWYT8.App\\Controller\\PrestationController::delete()'] = ($container->privates['.service_locator.2ibWYT8'] ?? $container->load('get_ServiceLocator_2ibWYT8Service'))->withContext('App\\Controller\\PrestationController::delete()', $container);
    }
}
