<?php

namespace ContainerBGMLLhV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestationControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qCVllgb.App\Controller\PrestationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qCVllgb.App\\Controller\\PrestationController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'prestation' => ['privates', '.errored..service_locator.qCVllgb.App\\Entity\\Prestation', NULL, 'Cannot autowire service ".service_locator.qCVllgb": it needs an instance of "App\\Entity\\Prestation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'prestation' => 'App\\Entity\\Prestation',
        ]))->withContext('App\\Controller\\PrestationController::index()', $container);
    }
}
