<?php

namespace ContainerBGMLLhV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qCVllgb.App\Entity\Prestation' shared service.
     *
     * @return \App\Entity\Prestation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.qCVllgb": it needs an instance of "App\\Entity\\Prestation" but this type has been excluded in "config/services.yaml".');
    }
}
