<?php

namespace ContainerQ6Euvx9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2ibWYT8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2ibWYT8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2ibWYT8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'prestation' => ['privates', '.errored..service_locator.2ibWYT8.App\\Entity\\Prestation', NULL, 'Cannot autowire service ".service_locator.2ibWYT8": it needs an instance of "App\\Entity\\Prestation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'prestation' => 'App\\Entity\\Prestation',
        ]);
    }
}
