<?php

namespace ContainerQ6Euvx9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthenticatorControlleronLogoutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rlkk1pd.App\Controller\AuthenticatorController::onLogout()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rlkk1pd.App\\Controller\\AuthenticatorController::onLogout()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event' => ['privates', '.errored..service_locator.rlkk1pd.Symfony\\Component\\Security\\Http\\Event\\LogoutEvent', NULL, 'Cannot autowire service ".service_locator.rlkk1pd": it references class "Symfony\\Component\\Security\\Http\\Event\\LogoutEvent" but no such service exists.'],
        ], [
            'event' => 'Symfony\\Component\\Security\\Http\\Event\\LogoutEvent',
        ]))->withContext('App\\Controller\\AuthenticatorController::onLogout()', $container);
    }
}
