<?php

namespace ContainerQ6Euvx9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTurbo_Mercure_Default_RendererService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'turbo.mercure.default.renderer' shared service.
     *
     * @return \Symfony\UX\Turbo\Bridge\Mercure\TurboStreamListenRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-turbo/src/Twig/TurboStreamListenRendererInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-turbo/src/Bridge/Mercure/TurboStreamListenRenderer.php';

        $a = ($container->privates['stimulus.helper'] ?? self::getStimulus_HelperService($container));

        if (isset($container->privates['turbo.mercure.default.renderer'])) {
            return $container->privates['turbo.mercure.default.renderer'];
        }

        return $container->privates['turbo.mercure.default.renderer'] = new \Symfony\UX\Turbo\Bridge\Mercure\TurboStreamListenRenderer(($container->privates['mercure.hub.default.traceable'] ?? self::getMercure_Hub_Default_TraceableService($container)), $a, ($container->privates['turbo.id_accessor'] ?? $container->load('getTurbo_IdAccessorService')));
    }
}
