<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_hotwired_turbo_dist_turbo_es2017-esm_js-node_modules_symfony_stimulus-br-2d3bfc.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
        'login' => [
            'js' => [
                '/build/runtime.js',
                '/build/login.js',
            ],
            'css' => [
                '/build/login.css',
            ],
        ],
    ],
],

]];
